INSERT INTO books (title, author, price, image) VALUES
('The Lord of the Rings', 'J.R.R. Tolkien', 19.99, NULL),
('The Hobbit', 'J.R.R. Tolkien', 14.99, NULL),
('A Game of Thrones', 'George R.R. Martin', 24.99, NULL),
('The Name of the Wind', 'Patrick Rothfuss', 16.99, NULL),
('The Way of Kings', 'Brandon Sanderson', 22.99, NULL),
('Mistborn: The Final Empire', 'Brandon Sanderson', 18.99, NULL),
('Harry Potter and the Sorcerer’s Stone', 'J.K. Rowling', 12.99, NULL),
('The Lies of Locke Lamora', 'Scott Lynch', 17.99, NULL),
('The Blade Itself', 'Joe Abercrombie', 15.99, NULL),
('The Wheel of Time: The Eye of the World', 'Robert Jordan', 20.99, NULL),
('The Once and Future King', 'T.H. White', 14.49, NULL),
('The Magician’s Nephew', 'C.S. Lewis', 11.99, NULL),
('Jonathan Strange & Mr Norrell', 'Susanna Clarke', 19.49, NULL),
('The Priory of the Orange Tree', 'Samantha Shannon', 21.99, NULL),
('The Poppy War', 'R.F. Kuang', 17.49, NULL),
('The Broken Empire: Prince of Thorns', 'Mark Lawrence', 16.49, NULL),
('The Black Prism', 'Brent Weeks', 18.49, NULL),
('American Gods', 'Neil Gaiman', 14.99, NULL);
